name: Generate Ascii Artwork
on: push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repository
          uses: actions/checkout@v4
        - name: install cowsay command
          run: sudo apt-get update
               sudo apt-get install cowsay -y
        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a Dragon.....RAWRRRR...." >> dragon.txt
        - name: Test file existence
          run: grep -i "dragon" dragon.txt 
        - name: Read dragon.txt file
          run: cat dragon.txt
        - name: checkout repo files
          run: ls