name: Generate Ascii Artwork
on: push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repository
          uses: actions/checkout@v4
        - name: list files in CWD
          run: |
               cd ./.github/workflows
               ls
               chmod a+x ./ascii-sript.sh
        - name: Executing Shell Script
          run: ./ascii-sript.sh
